---
antivirus.settings:
  type: config_object
  label: 'Antivirus settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    require_scan:
      type: boolean
      label: 'File must be scanned'
    require_clean:
      type: boolean
      label: 'File must not be infected'
